= Maximo Connector
:keywords: Maximo, IBM, IBM Maximo, Mule connector, Integration Works
:toc: macro
:toclevels: 2

toc::[]

[[overview]]
== Overview

The Anypoint connector for Maximo (Maximo connector) enables you to connect Mule flows to the Maximo system using the Maximo Web API.

Read through this user guide to understand how to set up and configure a basic flow using the Maximo connector. Track feature additions, compatibility, limitations and API version updates with each release of the connector using the link:https://github.com/IntegrationWorksAus/mule-maximo-connector-mule-4/tree/main/release-notes-adoc[Release Notes]. Review the connector operations and functionality using the link:/link-to-github.io-or-internal-section[Technical Reference] alongside the link:https://www.mulesoft.com/exchange#!/?filters=Salesforce&sortBy=rank[demo applications].

MuleSoft maintains this connector under the link:https://www.mulesoft.com/legal/versioning-back-support-policy#anypoint-connectors[MuleSoft Certified] support policy.

[[important-concepts]]
== Important Concepts

This document assumes that you are familiar with Mule,
link:https://docs.mulesoft.com/connectors/introduction/introduction-to-anypoint-connectors[Anypoint Connectors], and
link:https://docs.mulesoft.com/mule-runtime/4.3/intro-studio[Anypoint Studio 7]. To increase your familiarity with Studio, consider completing a link:https://docs.mulesoft.com/studio/7.3/[Anypoint Studio Tutorial]. This page requires some basic knowledge of link:https://docs.mulesoft.com/general/api-led-overview[Mule Concepts], link:https://docs.mulesoft.com/mule-runtime/4.2/about-components#components[Elements in a Mule Flow], and link:https://docs.mulesoft.com/mule-runtime/4.2/global-elements[Global Elements].


[[requirements]]
== Hardware and Software Requirements

For hardware and software requirements, please visit the link:https://github.com/IntegrationWorksAus/mule-maximo-connector-mule-4/tree/main/release-notes-adoc[Release Notes].

[[install]]
== How to Install

You can install the connector in Anypoint Studio using the instructions in
link:https://docs.mulesoft.com/mule-runtime/3.9/installing-connectors[Installing a Connector from Anypoint Exchange].

[[upgrading]]
=== Upgrading from an Older Version

If you’re currently using an older version of the connector, a small popup appears in the bottom right corner of Anypoint Studio with an "Updates Available" message.

. Click the popup and check for available updates. 
. Click the Connector version checkbox and click *Next* and follow the instructions provided by the user interface. 
. *Restart* Studio when prompted. 
. After restarting, when creating a flow and using the connector, if you have several versions of the connector installed, you may be asked which version you would like to use. Choose the version you would like to use.

Additionally, we recommend that you keep Studio up to date with its latest version.

[[ns-schema]]
== Connector Namespace and Schema

When designing your application in Studio, the act of dragging the connector from the palette onto the Anypoint Studio canvas should automatically populate the XML code with the connector *namespace* and *schema location*.

*Namespace:* `+http://www.mulesoft.org/schema/mule/maximo+`
*Schema Location:* `+http://www.mulesoft.org/schema/mule/maximo/current/mule-maximo.xsd+`

[TIP]
If you are manually coding the Mule application in Studio's XML editor or other text editor, define the namespace and schema location in the header of your *Configuration XML*, inside the `<mule>` tag.

[source, xml,linenums]
----

<mule xmlns="http://www.mulesoft.org/schema/mule/core"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:maximo="http://www.mulesoft.org/schema/mule/maximo"
    xsi:schemaLocation="http://www.mulesoft.org/schema/mule/core
                        http://www.mulesoft.org/schema/mule/core/current/mule.xsd
                        http://www.mulesoft.org/schema/mule/maximo
                        http://www.mulesoft.org/schema/mule/maximo/current/mule-maximo.xsd">

      <!-- put your global configuration elements and flows here -->

</mule>
----

[[maven]]
== Maven Dependency Information

For Maven dependency management, include this XML snippet in your `pom.xml` file.

[source,xml,linenums]
----

     <dependency>
      <groupId>org.mule.modules</groupId>
      <artifactId>maximo-mule-connector</artifactId>
      <version>${version}</version>
      <classifier>mule-plugin</classifier>
     </dependency>

----

[TIP]
Inside the `<version>` tags, put the desired version number, the word `RELEASE` for the latest release, or `SNAPSHOT` for the latest available version.

[[configure]]
== How to Configure

Place the connector into your flow as applicable for your use case.

To use the Maximo connector in your Mule application, you must configure a global Maximo element that can be used by the Maximo connector (read more about  link:link:https://docs.mulesoft.com/mule-runtime/4.2/global-elements[Global Elements]). The Maximo connector offers the following global configuration(s), requiring the following credentials: *Hostname*, *Port*, *Username*, *Password*...etc.

[%header,cols="50a,50a"]
|===
|Field |Description
|*Hostname* |Enter the host to connect with Maximo.
|*Port* |Enter the host to connect with Maximo.
|*Username* |Enter the username to log into Maximo.
|*Password* |Enter the corresponding password.

|===

[[operations]]

== Operations

==== Create Object

Create elements in the Asset database.

==== Read Object

Get a Maximo Object details.

==== Remove Object

Delete a Maximo Object.

==== Update Object

Update a Maximo Object's details.

== Common Use Cases

=== Use Case 1: Create a new MXASSET object

This use case demonstrates the creation of a new MXASSET object in a Maximo demo server. 

      - Checkout the following demo link:https://github.com/IntegrationWorksAus/mule-maximo-connector-mule-4/tree/main/demo[Maximo Demo]
      
      - Run the application
      
      - Make the following request with a REST Client (e.g. Postman)


===== Request

----

GET http://localhost:8081/create

----

===== Body

----

{
  "spi:autowogen": false,
  "spi:itemsetid": "SET1",
  "spi:iscalibration": false,
  "spi:assetnum": "ASSETABC",
  "spi:removefromactivesp": false,
  "assetspec_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetspecclass",
  "spi:siteid": "BEDFORD",
  "spi:tloampartition": false,
  "spi:assettype": "PRODUCTION",
  "spi:budgetcost": 0.0,
  "spi:disabled": false,
  "spi:isrunning": true,
  "rdf:about": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--",
  "spi:changepmstatus": false,
  "spi:totunchargedcost": 0.0,
  "spi:invcost": 0.0,
  "spi:moved": false,
  "spi:status_description": "Operating",
  "assetopskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetopskd",
  "spi:pluscismte": false,
  "spi:pluscsolution": false,
  "assetmeter_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/int_assetmeter",
  "spi:status": "OPERATING",
  "spi:pluscisinhousecal": false,
  "spi:changeby": "MAXIMO",
  "spi:orgid": "EAGLENA",
  "spi:assetid": 15523454326,
  "spi:unchargedcost": 0.0,
  "assetusercust_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetusercust",
  "spi:expectedlife": 0,
  "spi:ytdcost": 0.0,
  "spi:rolltoallchildren": false,
  "spi:pluscpmextdate": false,
  "spi:totdowntime": 0.0,
  "spi:islinear": false,
  "spi:mainthierchy": false,
  "spi:totalcost": 0.0,
  "spi:newsite": "BEDFORD",
  "spi:description": "Asset 1",
  "spi:plusciscontam": false,
  "spi:returnedtovendor": false,
  "spi:children": true,
  "spi:replacecost": 0.0,
  "assetmntskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetmntskd",
  "spi:removefromactiveroutes": false,
  "spi:assettype_description": "Production Assets",
  "spi:purchaseprice": 0.0
}
----

===== Response

----

{
    "spi:autowogen": false,
    "spi:itemsetid": "SET1",
    "_rowstamp": "2658593",
    "spi:iscalibration": false,
    "spi:assetnum": "ASSETABC",
    "spi:removefromactivesp": false,
    "assetspec_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetspecclass",
    "spi:siteid": "BEDFORD",
    "spi:tloampartition": false,
    "spi:assettype": "PRODUCTION",
    "spi:budgetcost": 0.0,
    "spi:disabled": false,
    "spi:isrunning": true,
    "rdf:about": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--",
    "spi:changepmstatus": false,
    "spi:totunchargedcost": 0.0,
    "spi:invcost": 0.0,
    "spi:moved": false,
    "spi:status_description": "Operating",
    "assetopskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetopskd",
    "spi:pluscismte": false,
    "spi:pluscsolution": false,
    "assetmeter_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/int_assetmeter",
    "spi:status": "OPERATING",
    "spi:pluscisinhousecal": false,
    "spi:changeby": "MAXIMO",
    "spi:orgid": "EAGLENA",
    "spi:assetid": 15523454326,
    "spi:unchargedcost": 0.0,
    "assetusercust_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetusercust",
    "spi:expectedlife": 0,
    "spi:ytdcost": 0.0,
    "spi:rolltoallchildren": false,
    "spi:pluscpmextdate": false,
    "spi:totdowntime": 0.0,
    "spi:islinear": false,
    "spi:mainthierchy": false,
    "spi:statusdate": "2021-07-02T05:50:13-04:00",
    "spi:totalcost": 0.0,
    "spi:newsite": "BEDFORD",
    "spi:description": "Asset 1",
    "spi:plusciscontam": false,
    "spi:returnedtovendor": false,
    "spi:children": true,
    "prefixes": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "spi": "http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#",
        "oslc": "http://open-services.net/ns/core#"
    },
    "spi:replacecost": 0.0,
    "assetmntskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetmntskd",
    "spi:changedate": "2021-07-02T05:50:13-04:00",
    "spi:removefromactiveroutes": false,
    "spi:assettype_description": "Production Assets",
    "spi:purchaseprice": 0.0
}

----

=== Use Case 2: Read details from a Maximo Object

      - Checkout the following demo - link:https://github.com/IntegrationWorksAus/mule-maximo-connector-mule-4/tree/main/demo[Maximo Demo]
      - Run the application
      
      - Make the following request with a REST Client (e.g. Postman)

===== Request

----

GET http://localhost:8081/read

----

===== Response
If the asset does not exist on the server:
----
{
    "prefixes": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "oslc": "http://open-services.net/ns/core#"
    },
    "oslc:responseInfo": {
        "rdf:about": "http://nothing/os/mxasset?oslc.select=%2A&oslc.where=assetid%3D15523454326"
    },
    "rdfs:member": [],
    "rdf:about": "http://nothing/os/mxasset"
}
----
If the asset does exist on the server:
----
{
    "prefixes": {
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
        "spi": "http://jazz.net/ns/ism/asset/smarter_physical_infrastructure#",
        "oslc": "http://open-services.net/ns/core#"
    },
    "oslc:responseInfo": {
        "rdf:about": "http://nothing/os/mxasset?oslc.select=%2A&oslc.where=assetid%3D15523454326"
    },
    "rdfs:member": [
        {
            "spi:autowogen": false,
            "spi:itemsetid": "SET1",
            "_rowstamp": "2658593",
            "spi:iscalibration": false,
            "spi:assetnum": "ASSETABC",
            "spi:removefromactivesp": false,
            "assetspec_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetspecclass",
            "spi:siteid": "BEDFORD",
            "spi:tloampartition": false,
            "spi:assettype": "PRODUCTION",
            "spi:budgetcost": 0.0,
            "spi:disabled": false,
            "spi:isrunning": true,
            "rdf:about": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--",
            "spi:changepmstatus": false,
            "spi:totunchargedcost": 0.0,
            "spi:invcost": 0.0,
            "spi:moved": false,
            "spi:status_description": "Operating",
            "assetopskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetopskd",
            "spi:pluscismte": false,
            "spi:pluscsolution": false,
            "assetmeter_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/int_assetmeter",
            "spi:status": "OPERATING",
            "spi:pluscisinhousecal": false,
            "spi:changeby": "MAXIMO",
            "spi:orgid": "EAGLENA",
            "spi:assetid": 15523454326,
            "spi:unchargedcost": 0.0,
            "assetusercust_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetusercust",
            "spi:expectedlife": 0,
            "spi:ytdcost": 0.0,
            "spi:rolltoallchildren": false,
            "spi:pluscpmextdate": false,
            "spi:totdowntime": 0.0,
            "spi:islinear": false,
            "spi:mainthierchy": false,
            "spi:statusdate": "2021-07-02T05:50:13-04:00",
            "spi:totalcost": 0.0,
            "spi:newsite": "BEDFORD",
            "spi:description": "Asset 1",
            "spi:plusciscontam": false,
            "spi:returnedtovendor": false,
            "spi:children": true,
            "spi:replacecost": 0.0,
            "assetmntskd_collectionref": "http://nothing/os/mxasset/_QVNTRVRBQkMvQkVERk9SRA--/assetmntskd",
            "spi:changedate": "2021-07-02T05:50:13-04:00",
            "spi:removefromactiveroutes": false,
            "spi:assettype_description": "Production Assets",
            "spi:purchaseprice": 0.0
        }
    ],
    "rdf:about": "http://nothing/os/mxasset"
}
----


== Resources

* Access the link:https://github.com/IntegrationWorksAus/mule-maximo-connector-mule-4/tree/main/release-notes-adoc[Maximo Connector Release Notes].